src/KPcore/Controllers/AdminController.cs
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using KPcore.Data;
using KPcore.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using KPcore.Models;
using KPcore.Services;
using KPcore.ViewModels.AdminViewModels;

namespace KPcore.Controllers
{
    [Authorize]
    public class AdminController : BaseController
    {
        private readonly ISubjectRepository _subjectRepository;
        private readonly IUserRepository _userRepository;

        public AdminController(
            UserManager<ApplicationUser> userManager,
            INotificationRepository notificationRepository,
            IUserRepository userRepository,
            ISubjectRepository subjectRepository) : base(userManager, notificationRepository)
        {
            _subjectRepository = subjectRepository;
            _userRepository = userRepository;
        }

        // GET: /Admin/Index
        [HttpGet]
        public async Task<IActionResult> Index(AdminMessageId? message = null)
        {
            ViewData["StatusMessage"] =
                message == AdminMessageId.AddSubjectSuccess ? "Nowy przedmiot został dodany pomyślnie."
                : message == AdminMessageId.Error ? "Wystąpił błąd."
                : message == AdminMessageId.RemoveSubjectSuccess ? "Przedmiot został usunięty pomyślnie."
                : message == AdminMessageId.RemoveSubjectFailed ? "Nie udało się usunąć przedmiotu: nie jesteś Adminem!"
                : "";

            var user = await GetCurrentUserAsync();
            if (user == null || user.Status != 2)
            {
                return View("Error");
            }
            var model = new AdminIndexViewModel
            {
                Subjects = _subjectRepository.ListAll()
            };
            return View(model);
        }

        // GET: /Admin/Subject
        public async Task<IActionResult> Subject(int? id)
        {
            var user = await GetCurrentUserAsync();
            if (user == null || user.Status != 2)
            {
                return RedirectToAction(nameof(Index), "Home", new { AdminMessageId.Error });
            }

            var subject = _subjectRepository.FindSubjectById(id);
            var model = new SubjectViewModel();

            ViewData["Title"] = "Dodaj przedmiot";
            if (subject != null)
            {
                model.SubjectId = subject.Id;
                model.Name = subject.Name;
                model.Description = subject.Description;
                ViewData["Title"] = "Edytuj przedmiot";
            }
            return View(model);
        }


        // POST: /Group/Subject
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Subject(SubjectViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await GetCurrentUserAsync();
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Akcja zakończyła się niepowodzeniem.");
                return View(model);
            }

            var subject = new Subject
            {
                Id = 1,
                Name = model.Name,
                Description = model.Description,
            };

            if (model.SubjectId == null)
            {
                _subjectRepository.AddSubject(subject);
            }
            else
            {
                subject.Id = model.SubjectId.Value;
                _subjectRepository.EditSubject(subject);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> RemoveSubject(int id)
        {
            var user = await GetCurrentUserAsync();
            if (user == null || user.Status != 2)
            {
                return RedirectToAction(nameof(Index), new { Message = AdminMessageId.RemoveSubjectFailed });
            }
            var subject = _subjectRepository.FindSubjectById(id);
            _subjectRepository.RemoveSubject(subject);
            return RedirectToAction(nameof(Index), new { Message = AdminMessageId.RemoveSubjectSuccess });
        }
        
        [HttpPost]
        public JsonResult NotifyEveryone(string message)
        {
            var user = GetCurrentUserAsync().Result;
            if (user == null || user.Status != 2)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Nie możesz tego zrobić!");
            }

            var allUsers = _userRepository.GetAllUsers().ToList();
            _notificationRepository.AddNotificationToMultipleUsers(message, allUsers);

            Response.StatusCode = (int)HttpStatusCode.OK;
            return Json("Wysłano wszystkim podaną notyfikację.");
        }
        
        [HttpPost]
        public JsonResult CleanSeenNotifications()
        {
            var user = GetCurrentUserAsync().Result;
            if (user == null || user.Status != 2)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Nie możesz tego zrobić!");
            }
            
            _notificationRepository.CleanNotifications();
            Response.StatusCode = (int)HttpStatusCode.OK;
            return Json("Wyczyszczono przeczytane notyfikacje.");
        }
        #region Helpers

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

        public enum AdminMessageId
        {
            AddSubjectSuccess,
            Error,
            RemoveSubjectSuccess,
            RemoveSubjectFailed
        }

        #endregion
    }
}

src/KPcore/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using KPcore.Interfaces;
using KPcore.Models;
using KPcore.ViewModels.GroupViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;

namespace KPcore.Controllers
{
    [Authorize]
    public class GroupController : BaseController
    {
        private readonly IGroupRepository _groupRepository;
        private readonly IUserRepository _userRepository;
        private readonly ITopicRepository _topicRepository;
        private readonly IDeadlineRepository _deadlineRepository;

        public GroupController(UserManager<ApplicationUser> userManager,
            IGroupRepository groupRepository,
            ITopicRepository topicRepository,
            IDeadlineRepository deadlineRepository,
            INotificationRepository notificationRepository,
            IUserRepository userRepository) : base(userManager, notificationRepository)
        {
            _groupRepository = groupRepository;
            _topicRepository = topicRepository;
            _deadlineRepository = deadlineRepository;
            _userRepository = userRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Index(GroupMessageId? message = null)
        {
            ViewData["StatusMessage"] =
                message == GroupMessageId.CreateGroupSuccess ? "Nowa grupa została utworzona."
                : message == GroupMessageId.NoGroupToView ? "Nie ma takiej grupy."
                : message == GroupMessageId.ErrorAddingCommentToGroup ? "Błąd podczas dodawania nowego komentarza."
                : message == GroupMessageId.LeaveGroupSuccess ? "Opuściłeś grupę."
                : message == GroupMessageId.DeleteGroupSuccess ? "Usunąłeś grupę."
                : message == GroupMessageId.Error ? "Wystąpił błąd."
                : message == GroupMessageId.NameChanged ? "Pomyślnie zmieniono nazwę grupy."
                : message == GroupMessageId.NameChangeError ? "Wystąpił błąd podczas zmieniana nazwy grupy: nieprawidłowa nazwa."
                : "";

            var user = await GetCurrentUserAsync();
            var _StudentGroups = _groupRepository.GetAllUsersGroup(user.Id);
            Dictionary<StudentGroup, GroupComment> dict = new Dictionary<StudentGroup, GroupComment>();
            foreach (var group in _StudentGroups)
            {
                var comment = _groupRepository.GetLatestComment(group.GroupId) ?? new GroupComment
                {
                    Content = "Brak"
                };
                dict.Add(group, comment);
            }
            var model = new StudentGroupIndexViewModel
            {
                StudentGroups = dict
            };

            return View(model);
        }

        // GET: /Group/Create
        public IActionResult Create()
        {
            return View(new GroupViewModel());
        }

        // POST: /Group/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(GroupViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await GetCurrentUserAsync();
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Nie udało się stworzyć nowej grupy.");
                return View(model);
            }

            var group = new Group
            {
                Id = 1,
                Name = model.Name
            };

            _groupRepository.CreateGroup(group, user.Id);
            return RedirectToAction(nameof(Index), new { Message = GroupMessageId.CreateGroupSuccess });
        }

        // GET: /Group/Details
        [HttpGet]
        public IActionResult Details(int id = 0)
        {
            var group = _groupRepository.GetGroupById(id);

            if (group == null)
            {
                return RedirectToAction(nameof(Index), new { Message = GroupMessageId.NoGroupToView });
            }

            var studentsList = _groupRepository.GetStudentsOfGroup(id);

            var model = new GroupDetailsViewModel
            {
                Id = group.Id,
                Name = group.Name,
                TopicId = group.TopicId,
                Topic = group.Topic,
                StudentsList = studentsList,
                GroupLeader = _groupRepository.GetLeader(id),
                GroupComments = _groupRepository.GetGroupComments(id)
            };

            return View(model);
        }

        public async Task<IActionResult> EditGroupName(GroupDetailsViewModel model)
        {
            var user = await GetCurrentUserAsync();
            var groupLeader = _groupRepository.GetLeader(model.Id);
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index), new { message = GroupMessageId.NameChangeError });
            }
            if (user.Id == groupLeader.Id)
            {
                var group = _groupRepository.GetGroupById(model.Id);
                group.Name = model.Name;
                _groupRepository.EditGroup(group);
                return RedirectToAction(nameof(Index), new { Message = GroupMessageId.NameChanged });
            }
            return RedirectToAction(nameof(Index), new { message = GroupMessageId.Error });
        }

        public async Task<IActionResult> DeleteGroup(int id)
        {
            var group = _groupRepository.GetGroupById(id);
            var user = await GetCurrentUserAsync();

            var groupLeader = _groupRepository.GetLeader(id);
            if (user != null && groupLeader.Id == user.Id)
            {
                _groupRepository.DeleteGroup(id);
            }
            return RedirectToAction(nameof(Index), new { Message = GroupMessageId.DeleteGroupSuccess });
        }

        #region GroupComments 

        // GET: /Group/Comment
        public IActionResult Comment(int groupid, int? commentid)
        {
            var group = _groupRepository.GetGroupById(groupid);
            if (group == null)
            {
                return RedirectToAction(nameof(Index), new { Message = GroupMessageId.ErrorAddingCommentToGroup });
            }
            var model = new GroupCommentViewModel
            {
                Group = @group,
                GroupId = groupid
            };

            var comment = _groupRepository.GetCommentById(commentid);
            if (comment != null)
            {
                model.CommentId = commentid;
                model.Content = comment.Content;
                model.CreationDate = comment.CreationDate.Value;
                ViewData["Title"] = "Edytuj komentarz";
            }
            else
            {
                ViewData["Title"] = "Dodaj komentarz";
            }

            return View(model);
        }

        // POST: /Group/Comment
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Comment(GroupCommentViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await GetCurrentUserAsync();
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Akcja zakończyła się niepowodzeniem.");
                return View(model);
            }

            var comment = new GroupComment
            {
                GroupId = model.GroupId,
                AuthorId = user.Id,
                Content = model.Content,
            };

            if (model.CommentId == null)
            {
                comment.Id = 1;
                _groupRepository.AddComment(comment);

                var group = _groupRepository.GetGroupById(comment.GroupId);
                var notificationMsg = $"Pojawił się nowy komentarz w grupie [{group.Id}] {group.Name}";
                var groupMembers = _groupRepository.GetAllMembers(group.Id).Where(m => m.Id != user.Id).ToList();
                _notificationRepository.AddNotificationToMultipleUsers(notificationMsg, groupMembers);
            }
            else
            {
                comment.Id = model.CommentId.Value;
                comment.CreationDate = model.CreationDate;
                _groupRepository.EditComment(comment);
            }

            return RedirectToAction(nameof(Details), new { id = comment.GroupId });
        }

        public async Task<IActionResult> DeleteComment(int id)
        {
            var comment = _groupRepository.GetCommentById(id);
            var user = await GetCurrentUserAsync();

            if (comment.AuthorId == user.Id)
            {
                _groupRepository.DeleteComment(id);
            }
            return RedirectToAction(nameof(Details), new { id = comment.GroupId });
        }

        #endregion

        #region GroupMembers

        public async Task<IActionResult> RemoveMember(int groupid, int memberid)
        {
            var currentUser = await GetCurrentUserAsync();
            var groupLeader = _groupRepository.GetLeader(groupid);

            if (currentUser != null && currentUser.Id == groupLeader.Id)
            {
                var group = _groupRepository.GetGroupById(groupid);
                _groupRepository.RemoveMemberFromGroup(groupid, memberid);

                var notificationMsg = $"Zostałeś usunięty z grupy [{group.Id}] {group.Name}.";
                _notificationRepository.AddNotificationToUser(notificationMsg, memberid);
                return RedirectToAction(nameof(Details), new { id = groupid });
            }

            ModelState.AddModelError(string.Empty, "Nie udało się usunąć członka grupy.");
            return RedirectToAction(nameof(Details), new { id = groupid });
        }

src/KPcore/Views/Shared/_Layout.cshtml
@model KPcore.ViewModels.BaseViewModel
@inject SignInManager<ApplicationUser> SignInManager
@{
    var userStatus = -1;
    var isLoggedIn = SignInManager.IsSignedIn(User);
    if (isLoggedIn)
    {
        userStatus = Model.CurrentUser.Status;
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KPcore</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/siteless.css" />
        <link rel="stylesheet" href="~/css/baloons.css" />

        <script src="https://use.fontawesome.com/73a5b52f13.js"></script>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>



<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <img class="logo" alt="Kuźnia Projektów Logo" src="~/images/LogoCropped.png" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{ if (isLoggedIn)
                        {
                            if (userStatus == 0 || userStatus == 2)
                            {
                                <li>@Html.ActionLink("Twoje grupy", "Index", "Group")</li>
                            }
                            if (userStatus == 1 || userStatus == 2)
                            {

                                <li>@Html.ActionLink("Twoje tematy", "Index", "Topic")</li>
                            }
                            if (userStatus == 2)
                            {
                                <li>@Html.ActionLink("Panel admina", "Index", "Admin")</li>
                            }
                        }
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - KPcore</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>