src/KPcore/Models/Deadline.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace KPcore.Models
{
    public class Deadline
    {
        public int Id { get; set; }

        public int GroupId { get; set; }

        public Group Group { get; set; }

        public DateTime DeadlineDate { get; set; }

        public float? Mark { get; set; }

        [StringLength(500)]
        public string Comment { get; set; }

        public string GetDateAndTime => DeadlineDate.Day + "." + DeadlineDate.Month + "." + DeadlineDate.Year + ", " + DeadlineDate.Hour + ":" + DeadlineDate.Minute;
    }
}

src/KPcore/Models/Topic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace KPcore.Models
{
    public class Topic
    {
        public int Id { get; set; }

        [Required]
        public int TeacherId { get; set; }

        public ApplicationUser Teacher { get; set; }

        public int SubjectId { get; set; }
        public Subject Subject { get; set; }

        public DateTime CreationDate { get; set; }

        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [Required]
        [StringLength(255)]
        public string Description { get; set; }

        public DateTime? MeetingsDate { get; set; }
    }
}

src/KPcore/ViewModels/GroupViewModels/DeadlineViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using KPcore.Models;

namespace KPcore.ViewModels.GroupViewModels
{
    public class DeadlineViewModel : BaseViewModel
    {
        public Group Group { get; set; }

        public int GroupId { get; set; }
        public int TopicId { get; set; }

        [Required]
        [Display(Name = "Data terminu")]
        public DateTime? DeadlineDate { get; set; } = null;
        
        [Display(Name = "Komentarz")]
        [StringLength(500)]
        public string Comment { get; set; }
    }
}

src/KPcore/Controllers/TopicController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using KPcore.Interfaces;
using KPcore.Models;
using KPcore.ViewModels.TopicViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace KPcore.Controllers
{
    [Authorize]
    public class TopicController : BaseController
    {
        private readonly ITopicRepository _topicRepository;
        private readonly IGroupRepository _groupRepository;
        private readonly ISubjectRepository _subjectRepository;
        private readonly IDeadlineRepository _deadlineRepository;

        public TopicController(UserManager<ApplicationUser> userManager,
            ITopicRepository topicRepository,
            IGroupRepository groupRepository,
            IDeadlineRepository deadlineRepository,
            INotificationRepository notificationRepository,
            ISubjectRepository subjectRepository) : base(userManager, notificationRepository)
        {
            _topicRepository = topicRepository;
            _groupRepository = groupRepository;
            _subjectRepository = subjectRepository;
            _deadlineRepository = deadlineRepository;
        }

        public async Task<IActionResult> Index(TopicMessageId? message = null)
        {
            ViewData["StatusMessage"] =
                message == TopicMessageId.CreateTopicSuccess ? "Nowy temat został dodany pomyślnie."
                : message == TopicMessageId.NoTopicToView ? "Brak tematu do wyświetlenia."
                : message == TopicMessageId.ErrorAddingCommentToTopic ? "Nie udało się dodać komentarza."
                : message == TopicMessageId.Error ? "Wystąpił błąd."
                : message == TopicMessageId.TopicDeleted ? "Temat został pomyślnie usunięty."
                : message == TopicMessageId.AddDeadlineError ? "Wystąpił błąd podczas dodawania terminu."
                : message == TopicMessageId.NoTopicToEdit ? "Brak tematu do edycji."
                : "";

            var user = await GetCurrentUserAsync();
            var model = new TeacherTopicsIndexViewModel
            {
                Topics = _topicRepository.GetAllUsersTopics(user.Id)
            };

            return View(model);
        }

        // GET: /Topic/Create
        public IActionResult Create()
        {
            var subjects = _subjectRepository.ListAll();

            var model = new CreateTopicViewModel(subjects);

            ViewBag.SubjectList = model.SubjectList;
            return View(model);
        }

        // POST: /Topic/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTopicViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await GetCurrentUserAsync();
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Nie udało się utworzyć tematu.");
                return View(model);
            }

            var topic = new Topic
            {
                Id = 1,
                Title = model.Title,
                Description = model.Description,
                CreationDate = DateTime.Now,
                SubjectId = model.SelectedSubjectId,
                TeacherId = user.Id,
                MeetingsDate = model.MeetingsDate
            };

            _topicRepository.CreateTopic(topic);
            return RedirectToAction(nameof(Index), new { Message = TopicMessageId.CreateTopicSuccess });
        }


        // GET: /Topic/Details
        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Index), new { Message = TopicMessageId.NoTopicToView });
            }

            var topic = _topicRepository.GetTopicById(id);

            if (topic == null)
            {
                return RedirectToAction(nameof(Index), new { Message = TopicMessageId.NoTopicToView });
            }
            var group = _groupRepository.GetGroupByTopicId(id);
            var model = new TopicDetailsViewModel
            {
                Id = topic.Id,
                Title = topic.Title,
                Description = topic.Description,
                Teacher = topic.Teacher,
                Subject = topic.Subject,
                CreationDate = topic.CreationDate,
                MeetingsDate = topic.MeetingsDate,
                TopicComments = _topicRepository.GetTopicComments(id)
            };

            if (group != null)
            {
                model.Group = @group;
                model.GroupLeader = _groupRepository.GetLeader(@group.Id);
                model.GroupMembers = _groupRepository.GetStudentsOfGroup(@group.Id);
                model.Deadlines = _deadlineRepository.GetDeadlinesByGroup(@group.Id);
                if (model.Deadlines.Count() != 0)
                {
                    model.CurrentDeadline = _deadlineRepository.GetCurrentDeadline(@group.Id);
                }
            }

            return View(model);
        }

        // GET: /Topic/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var user = await GetCurrentUserAsync();
            var topic = _topicRepository.GetTopicById(id);

            if (user == null || topic == null || topic.TeacherId != user.Id)
            {
                return RedirectToAction(nameof(Index), new { Message = TopicMessageId.NoTopicToEdit });
            }

            var model = new EditTopicViewModel
            {
                TopicId = topic.Id,
                SubjectId = topic.SubjectId,
                CreationDate = topic.CreationDate,
                TeacherId = topic.TeacherId,
                Title = topic.Title,
                Description = topic.Description,
                MeetingsDate = topic.MeetingsDate
            };

            return View(model);
        }

        // POST: /Topic/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditTopicViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await GetCurrentUserAsync();
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Akcja zakończyła się niepowodzeniem.");
                return View(model);
            }

            var topic = new Topic
            {
                Id = model.TopicId,
                SubjectId = model.SubjectId,
                TeacherId = model.TeacherId,
                CreationDate = model.CreationDate,
                Title = model.Title,
                Description = model.Description,
                MeetingsDate = model.MeetingsDate
            };

            _topicRepository.EditTopic(topic);
            return RedirectToAction(nameof(Details), new { id = model.TopicId });
        }

        public async Task<IActionResult> DeleteTopic(int id)
        {
            var user = await GetCurrentUserAsync();
            var topic = _topicRepository.GetTopicById(id);
            if (topic.TeacherId == user.Id)
            {
                _topicRepository.DeleteTopic(id);
            }
            return RedirectToAction(nameof(Index), new { Message = TopicMessageId.TopicDeleted });
        }

        #region TopicEntries

        // GET: /Topic/Entry
        public IActionResult Entry(int topicid, int? commentid)
        {
            var topic = _topicRepository.GetTopicById(topicid);
            if (topic == null)
            {
                return RedirectToAction(nameof(Index), new { Message = TopicMessageId.ErrorAddingCommentToTopic });
            }
            var model = new TopicCommentViewModel
            {
                Topic = topic,
                TopicId = topicid
            };

            var comment = _topicRepository.GetCommentById(commentid);
            if (comment != null)
            {
                model.CommentId = commentid;
                model.Content = comment.Content;
                model.CreationDate = comment.CreationDate.Value;
                ViewData["Title"] = "Edytuj komentarz";
            }
            else
            {
                ViewData["Title"] = "Dodaj komentarz";
            }

            return View(model);
        }

        // POST: /Topic/Entry
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Entry(TopicCommentViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await GetCurrentUserAsync();
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Akcja zakończyła się niepowodzeniem.");
                return View(model);
            }

            var comment = new TopicEntry
            {
                Id = 1,
                TopicId = model.TopicId,
                AuthorId = user.Id,
                Content = model.Content,
            };

            if (model.CommentId == null)
            {
                var groupId = _topicRepository.GetGroupIdForTopic(comment.TopicId);
                if (groupId != 0)
                {
                    var topic = _topicRepository.GetTopicById(comment.TopicId);
                    var notificationMsg = $"Pojawił się nowy komentarz do tematu [{topic.Id}] {topic.Title}";

                    var users = _groupRepository.GetAllMembers(groupId).Where(m => m.Id != user.Id).Select(m => m.Id).ToList();
                    if (!users.Contains(topic.TeacherId) && topic.TeacherId != user.Id)
                        users.Add(topic.TeacherId);

                    _notificationRepository.AddNotificationToMultipleUsers(notificationMsg, users);
                }

src/KPcore/Views/Topic/Create.cshtml
@model CreateTopicViewModel

@{
    ViewData["Title"] = "Nowy temat";
}

<div class="title">
    <h2>@ViewData["Title"]</h2>
    <p class="text-success">@ViewData["StatusMessage"]</p>
    <hr />
</div>

<form asp-action="Create">
    <div class="form-horizontal custom-form">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <span asp-validation-for="Title" class="text-danger"></span>
        <div class="form-group">
            <label asp-for="Title" class="control-label"></label>
            <div>
                <input asp-for="Title" class="form-control" placeholder="Nazwa tematu" />
            </div>
        </div>

        <span asp-validation-for="Description" class="text-danger"></span>
        <div class="form-group">
            <label asp-for="Description" class="control-label"></label>
            <div>
                <textarea asp-for="Description" rows="6" class="form-control" placeholder=""></textarea>
            </div>
        </div>

        <span asp-validation-for="SelectedSubjectId" class="text-danger"></span>
        <div class="form-group">
            <label asp-for="SelectedSubjectId" class="control-label"></label>
            <div>
                <select asp-for="SelectedSubjectId" asp-items="ViewBag.SubjectList" class="form-control"></select>
            </div>
        </div>

        <span asp-validation-for="MeetingsDate" class="text-danger"></span>
        <div class="form-group">
            <label asp-for="MeetingsDate" class="control-label"></label>
            <div>
                <input asp-for="MeetingsDate" type="datetime-local" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Zatwierdź" class="btn btn-success" />
            <a asp-action="index" class="btn btn-danger">Anuluj</a>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/KPcore/Views/Topic/Details.cshtml
@model TopicDetailsViewModel

@{
    ViewData["Title"] = "Szczegóły";
    var teacher = (Model.Teacher.Id == Model.CurrentUser.Id);
}

<div class="container-fluid">
    <div class="row">
        <div class="border-transparent space-after space-before">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center group-title">
                    @Html.TextBoxFor(m => m.Group.Name, new { type = "hidden" })
                    <h1>TEMAT</h1>
                    <h1>
                        @if (Model.Group != null)
                        {
                            if (!teacher)
                            {
                                @Html.ActionLink(Model.Group.Name, "Details", "Group", new { id = Model.Group.Id })
                            }
                            else
                            {
                                @Model.Group.Name
                            }
                        }
                        else
                        {
                            <span>BRAK GRUPY</span>
                        }
                    </h1>
                    <hr class="hr-black" />
                    <h2>Przedmiot: <b>@Html.DisplayFor(model => model.Subject.Name)</b></h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 col-md-offset-1 topic-description">
                    <h1>@Html.DisplayFor(model => model.Title)</h1>
                    <h2>Prowadzący: @Html.DisplayFor(model => model.Teacher.FirstName) @Html.DisplayFor(model => model.Teacher.LastName)</h2>
                    <span class="date">Data dodania: </span>
                    <span class="bold">@Html.DisplayFor(model => model.CreationDate)</span>
                    @if (Model.MeetingsDate != null)
                    {
                        <p>
                            <span class="date">Termin spotkań: </span>
                            <span class="bold">@Model.MeetingsDate.Value.DayOfWeek @Model.MeetingsDate.Value.Hour:@Model.MeetingsDate.Value.Minute</span>
                        </p>
                    }
                </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
                        Zarządzaj tematem <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            @if (Model.Group != null && teacher)
                            {
                                @Html.ActionLink("Dodaj nowy termin", "AddDeadline", "Group", new { id = Model.Group.Id })
                                @Html.ActionLink("Usuń grupę", "KickGroupFromTopic", "Group", new { topicid = Model.Id, groupid = Model.Group.Id, }, new { onclick = "return confirm('Na pewno chcesz usunąć grupę z tego tematu?');" })
                            }
                            @if (teacher)
                            {
                                @Html.ActionLink("Edytuj temat", "Edit", "Topic", new { id = Model.Id, })
                            }
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row description border-transparent">
                <div class="col-md-3 topic-description-header">
                    <h1 class="thin">OPIS:</h1>
                </div>
                <div class="col-md-6">
                    <span>@Html.DisplayFor(model => model.Description)</span>
                </div>
                <div class="col-md-3"></div>
            </div>

        </div>
    </div>
    <!-- CONTENT -->
    <div class="row space-after ">
        <div class="col-md-12 text-center closest-deadline-title">
            <h2>NAJBLIŻSZY TERMIN CZĄSTKOWY:</h2>
            <h2 class="bold">
                @if (Model.CurrentDeadline == null)
            {
                    <span>Brak terminu do wyświetlenia.</span>
                }
                else
                {
                    @Model.CurrentDeadline.GetDateAndTime
                }
            </h2>
        </div>
    </div>
    <div class="row space-before">

        <!-- COMMENT SECTION START -->
        <div class="col-sm-8 border-transparent comment-section">
            @await Html.PartialAsync("_Comments")
        </div>
        <!-- COMMENT SECIONT END -->
        <!-- LIST -->
        <div class="col-sm-4 space-after side-panel">
            @await Html.PartialAsync("_Deadlines")
            @await Html.PartialAsync("_UserList")
        </div>
    </div>
    <!-- USER LIST END -->
</div>

src/KPcore/Views/Topic/Edit.cshtml
@model EditTopicViewModel

@{
    ViewData["Title"] = "Edytuj temat";
}
<div class="title">
    <h2>@ViewData["Title"]</h2>
    <p class="text-success">@ViewData["StatusMessage"]</p>
    <hr />
</div>

<form asp-action="Edit">
    <div class="form-horizontal custom-form">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @Html.TextBoxFor(m => m.TopicId, new { type = "hidden" })
        @Html.TextBoxFor(m => m.SubjectId, new { type = "hidden" })
        @Html.TextBoxFor(m => m.TeacherId, new { type = "hidden" })
        @Html.TextBoxFor(m => m.CreationDate, new { type = "hidden" })

        <span asp-validation-for="Title" class="text-danger"></span>
        <div class="form-group">
            <label class="control-label">Nazwa tematu:</label>
            <div>
                <input asp-for="Title" class="form-control" placeholder="Nazwa tematu" />
            </div>
        </div>

        <span asp-validation-for="Description" class="text-danger"></span>
        <div class="form-group">
            <label class="control-label">Opis:</label>
            <div>
                <textarea asp-for="Description" rows="5" class="form-control"></textarea>
            </div>
        </div>

        <span asp-validation-for="MeetingsDate" class="text-danger"></span>
        <div class="form-group">
            <label class="control-label">Data spotkań:</label>
            <div>
                <input asp-for="MeetingsDate" type="datetime-local" class="form-control" />
            </div>
        </div>

        <div class="form-group ">
            <input type="submit" value="Zatwierdź" class="btn btn-success" />
            @Html.ActionLink("Wróć", "Details", new { id = Model.TopicId }, new { @class = "btn btn-grey" })
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/KPcore/Views/Topic/Entry.cshtml
@model TopicCommentViewModel

<div class="title">
    <h2>@ViewData["Title"]</h2>
    <p class="text-success">@ViewData["StatusMessage"]</p>
    <hr />
</div>

<form asp-action="Entry">
    <div class="form-horizontal custom-form">
        <h4>Temat: @Model.Topic.Title</h4>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @Html.TextBoxFor(m => m.TopicId, new { type = "hidden" })
        @Html.TextBoxFor(m => m.CommentId, new { type = "hidden" })
        @Html.TextBoxFor(m => m.CreationDate, new { type = "hidden" })

        <span asp-validation-for="Content" class="text-danger"></span>
        <div class="form-group">
            <label asp-for="Content"></label>
            <div>
                <textarea asp-for="Content" rows="7" id="comment" class="form-control"></textarea>
            </div>
        </div>

        <div class="form-group ">
            <input type="submit" value="Zatwierdź" class="btn btn-success" />
            @Html.ActionLink("Wróć", "Details", new { id = Model.TopicId }, new { @class = "btn btn-grey" })
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/KPcore/Views/Topic/Index.cshtml
@model TeacherTopicsIndexViewModel
@{
    ViewData["Title"] = "Twoje tematy.";
}
<div class="title">
    <h2>@ViewData["Title"]</h2>
    <p class="text-success">@ViewData["StatusMessage"]</p>
    <hr />
</div>
<div class="container-fluid">

    <div class="row text-center">
        <div class="text-center table-wrapper-custom">
            @if (Model.Topics.Any())
            {
                <div class="table-custom">
                    <div class="row-custom header-custom">
                        <div class="cell-custom">Nazwa</div>
                        <div class="cell-custom">Opis</div>
                        <div class="cell-custom">Przedmiot</div>
                        <div class="cell-custom">Data utworzenia</div>
                        <div class="cell-custom">Termin spotkań</div>
                        <div class="cell-custom" th>Akcje</div>
                    </div>

                    @foreach (var t in Model.Topics)
                    {
                        <div class="row-custom">
                            <div class="cell-custom">
                                @Html.ActionLink(t.Title, "Details", new {id = t.Id})
                            </div>
                            <div class="cell-custom">@t.Description</div>
                            <div class="cell-custom">@t.Subject.Name</div>
                            <div class="cell-custom">@t.CreationDate</div>
                            <div class="cell-custom">
                                @if (t.MeetingsDate != null)
                                {
                                    <span>
                                        @t.MeetingsDate.Value.DayOfWeek @t.MeetingsDate.Value.Hour:@t.MeetingsDate.Value.Minute
                                    </span>
                                }
                                else
                                {
                                    <span>nie ustalono</span>
                                }
                            </div>
                            <div class="cell-custom">@Html.ActionLink("Usuń", "DeleteTopic", new {id = t.Id}, new {@class = "btn-small-grey", onclick = "return confirm('Na pewno chcesz usunąć ten temat?');"})</div>
                        </div>
                    }
                </div>
            }
            else
            {
                <h2 class="text-center">Nie dodałeś żadnych tematów.</h2>
            }
        </div>
    </div>
    <div class="row text-center space-before">
        <a asp-controller="Topic" asp-action="Create" class="btn btn-grey space-after">Stwórz nowy temat</a>
    </div>
</div>

src/KPcore/Views/Topic/_Comments.cshtml
@model KPcore.ViewModels.TopicViewModels.TopicDetailsViewModel

<div class="row">
    <!-- Add comment button -->
    <div class="col-sm-4 text-center col-sm-offset-2 add-comment ">
        <span class="text-center ">
            @Html.ActionLink("DODAJ KOMENTARZ", "Entry", "Topic", new { topicid = Model.Id, }, new { @class = "btn btn-grey" })
        </span>
    </div>
    <!-- Add comment button end-->
    <!-- Comments title-->
    <div class="col-md-4 text-center small-screen-invisible">
        <h2 class="inblock">KOMENTARZE</h2>
    </div>
    <div class="col-sm-2"></div>
    <!-- Comments title end-->
    <!-- Coherence -->
</div>

<hr class="hr-narrow-black" />
<!-- COMMENT START -->
@if (Model.TopicComments.Any())
{
    foreach (var c in Model.TopicComments)
    {
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1 single-comment">
                <div class="row">
                    <div class="col-sm-8 bold inblock">
                        @c.Author.FirstName @c.Author.LastName
                    </div>

                    <div class="col-sm-4 text-right inblock">
                        @if (Model.CurrentUser.Id == c.AuthorId)
                        {
                            @Html.ActionLink("Edytuj", "Entry", new { topicid = Model.Id, commentid = c.Id }, new { @class = "btn-edit btn-small-grey" })
                            @Html.ActionLink("Usuń", "DeleteComment", new { id = c.Id }, new { @class = "btn-delete btn-small-grey", onclick = "return confirm('Na pewno chcesz usunąć ten komentarz?');" })
                        }
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-sm-12">
                        @c.Content
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 thin font-grey">
                        <span>Data dodania:</span> <span class="bold">@c.CreationDate</span>
                    </div>
                </div>
                @if (c.ModificationDate != null)
                {
                    <div class="row">
                        <div class="col-sm-12 text-small thin font-grey">
                            <span>Data modyfikacji:</span> <span class="bold">@c.ModificationDate</span>
                        </div>
                    </div>
                }
            </div>
        </div>
    }
}
else
{
    <div class="col-sm-12 text-center">
        <h2>
            Na chwilę obecną brak komentarzy.
        </h2>
    </div>
}
<!-- COMMENT END -->

src/KPcore/Views/Topic/_Deadlines.cshtml
@model KPcore.ViewModels.TopicViewModels.TopicDetailsViewModel

@{
    var teacher = (Model.Teacher.Id == Model.CurrentUser.Id);
}
<div class="text-center group-list-sm border-transparent deadline-list-main">
    <h3>Terminy:<i class="fa fa-minus-square-o"></i></h3>
    <hr class="molten-core" />
    <ul class="list-unstyled deadline-list">
        @{
            if (Model.Deadlines != null && Model.Deadlines.Count() != 0)
            {
                foreach (var d in Model.Deadlines)
                {
                    <li>
                        <div class="list-item-info tooltip-cst">
                            <a href="#">
                                @d.GetDateAndTime | ocena:
                                @{
                                    if (d.Mark == null)
                                    {
                                        @:-
                                    }
                                    else
                                    {
                                        @d.Mark
                                    }
                                }
                                <br />

                            </a>
                            <div>
                                @{
                                    if (teacher)
                                    {
                                        @Html.ActionLink("oceń", "MarkDeadline", "Group", new { id = d.Id }, new { @class = "btn-small-grey" })
                                    }
                                }
                            </div>
                            <span class="tooltiptext">
                                Komentarz:
                                @{
                                    if (d.Comment != null && d.Comment.Length > 0)
                                    {
                                        @d.Comment
                                    }
                                    else
                                    {
                                        @:(Brak komentarza)
                                    }
                                }
                            </span>
                            <hr class="hr-narrow" />
                        </div>
                    </li>
                }
            }
            else
            {
                <li>
                    <div class="list-item-info">
                        Brak terminów do wyświetlenia. <hr class="hr-narrow" />
                    </div>
                </li>
            }
        }
    </ul>
    @if (Model.Group != null && teacher)
    {
        @Html.ActionLink("Dodaj nowy termin", "AddDeadline", "Group", new { id = Model.Group.Id, }, new { @class = "btn btn-grey space-after" })
    }
</div>

src/KPcore/Views/Topic/_UserList.cshtml
@model KPcore.ViewModels.TopicViewModels.TopicDetailsViewModel




<div class="text-center group-list-sm space-before border-transparent user-list-main">
    <h3>
        Członkowie: <i class="fa fa-minus-square-o"></i>
    </h3>
    <hr class="molten-core" />
    <ul class="list-unstyled user-list">
        @if (Model.Group != null)
        {
            <li>
                <div class="list-item-info">
                    Lider: <a href="#">@Model.GroupLeader.FirstName @Model.GroupLeader.LastName</a>
                    <hr/>
                </div>
            </li>
            foreach (var s in Model.GroupMembers)
            {
                <li>
                    <div class="list-item-info">
                        <a href="#">@s.FirstName @s.LastName</a>
                        <hr/>
                    </div>
                </li>
            }
        }
        else
        {
            <li>
                <div class="list-item-info">
                    Brak członków do wyświetlenia.
                    <hr/>
                </div>
            </li>
        }
    </ul>
</div>